# Generated by Django 3.1.3 on 2023-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20231228_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='text',
        ),
    ]
